AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  catalogItemsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: catalogItemsQueue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt catalogItemsQueueDL.Arn
        maxReceiveCount: 5

  catalogItemsQueueDL:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: catalogItemsQueueDL
      MessageRetentionPeriod: 86400

  createProductTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: createProductTopic

  # createProductTopicSubscription:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     Protocol: email
  #     TopicArn:
  #       Ref: createProductTopic
  #     Endpoint: your-email@example.com

  iamLambdaRoleExecution:
    Type: AWS::IAM::Role
    Properties:
      RoleName: catalogItemsQueue-lambda-role-execution
      Description: "Lambda execution role for catalogItemsQueue"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Logging_Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "arn:aws:logs:*:*:*"
        - PolicyName: DynamoDB_Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource: "*"
        - PolicyName: SNS_Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sns:*"
                Resource: "*"
        - PolicyName: SQS_Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:*"
                Resource:
                  - !GetAtt catalogItemsQueue.Arn
                  - !GetAtt catalogItemsQueueDL.Arn
