service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-openapi-documentation
  # - serverless-event-body-option
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iam:
    role: arn:aws:iam::043770472754:role/DynamoDBLamdaFullAccessRole


functions:
  products:
    handler: getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors:
            origin: "https://dqbw3kxelkxvj.cloudfront.net" # <-- Specify allowed origin
            headers: "*" # <-- Specify allowed headers
          request:
            schemas:
              application/json:
                schema: ${file(api_schema/get_product_list.schema.json)}
          documentation:
            summary: "Get all product"
            description: "Returns a array of all products"
            requestBody:
              description: ""
            requestModels:
              application/json: "application/json"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "Success"
                responseModels:
                  application/json: "application/json"
  productsId:
    handler: getProductsById.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          request:
            parameters:
              paths:
                productId: true
          cors:
            origin: "https://dqbw3kxelkxvj.cloudfront.net" # <-- Specify allowed origin
            headers: "*"
          documentation:
            summary: "Get product by id"
            description: "Returns specific product, if Id found."
            requestBody:
              description: ""
            requestModels:
              application/json: "application/json"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "Success"
                responseModels:
                  application/json: "application/json"
  putProduct:
    handler: putProduct.putProduct
    events:
      - http:
          path: /product
          method: put
          cors:
            origin: "https://dqbw3kxelkxvj.cloudfront.net" # <-- Specify allowed origin
            headers: "*"
          documentation:
            summary: "Put product."
            description: "Put product item into the DB."
            requestBody:
              description: ""
            requestModels:
              application/json: "application/json"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "Success"
                responseModels:
                  application/json: "application/json"
custom:
  documentation:
    version: "1"
    title: "Product API"
    description: "This is Product API"
    models: []
