service: import-service
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-lift

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: "s3:ListBucket"
          Resource: "arn:aws:s3:::aws-cloudx-bike-shop-product-import"
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::aws-cloudx-bike-shop-product-import/*"

# constructs:
#     catalogItemsQueue:
#         type: queue

functions:
  upload:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          # cors: true
          cors:
            origin: "https://dqbw3kxelkxvj.cloudfront.net"
            headers: "*"
  parse:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: aws-cloudx-bike-shop-product-import
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
    environment:
            QUEUE_URL: ${construct:catalogItemsQueue.queueUrl}